# Generated by Django 3.2.6 on 2021-08-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_products_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zip_code',
            field=models.SmallIntegerField(null='True'),
            preserve_default='True',
        ),
    ]
